AHP weights
PROMETHEE II

In [ ]:
import numpy as np

# Define the data from the image table
data = {
    "Project name": ["Kamuthi Solar Park", "Pavagada Solar Park", "Kurnool Solar Park", "Nathpa Jhakri Dam", "Sardar Sarovar Dam", "Koyna Hydroelectric Project", "Tirunelvell Wind Farm", "Coimbatore Wind Farm", "Muppandal Wind Farm"],
    "Operating capacity (MW) (B)": [648, 1400, 1000, 1500, 1450, 1920, 1350, 1800, 1500],
    "Electricity (MWh/Yr)(B)": [1350000, 1600000, 1400000, 4000000, 5000000, 6000000, 3200000, 3500000, 3000000],
    "Construction period(yr)(NB)": [0.67, 2, 2, 10, 15, 1.5, 2, 1.5, 1.5],
    "Capacity factor (%(D))": [23.8, 13, 16.147, 55, 50, 60, 33, 38, 35],
    "Investments (NB) crores)": [4550, 14800, 7000, 22000, 25000, 30000, 19000, 22000, 20000],
    "O & M (Crores/Year)(NB)":[42, 130, 65, 180, 200, 220, 140, 160, 150],
    "Land (ha)(9) & M (Crores/Yr)(NB)": [42, 130, 65, 180, 200, 220, 140, 150, 150],
    "Jobs (NB)": [8500, 8000, 2500, 2200, 2500, 2800, 1400, 1800, 1500]
}

# Select the relevant criteria for your analysis
criteria = ["Operating capacity (MW) (B)", "Electricity (MWh/Yr)(B)", "Construction period(yr)(NB)", "Capacity factor (%(D))", "Investments (NB) crores)", "O & M (Crores/Year)(NB)", "Land (ha)(9) & M (Crores/Yr)(NB)", "Jobs (NB)"]

# Convert data into a NumPy array
decision_matrix = np.array([data[c] for c in criteria])
decision_matrix = np.vstack([decision_matrix, np.ones(len(data['Project name']))])  # Add a row for weights

# AHP Weights
w = np.array([0.782738095, 0.621428571, 0.25125, 0.683683333, 0.266325245, 0.303270896, 0.66547619, 0.70963925])

# Preference thresholds (replace with your values based on importance)
p_threshold = np.array([100, 500000, 1, 5, 2000, 90, 50, 500])

def promethee_ii(decision_matrix, p_threshold, w):
  """
  Performs PROMETHEE II MCDM method ranking.

  Args:
      decision_matrix (numpy.ndarray): Decision matrix with alternatives as rows and criteria as columns.
      p_threshold (numpy.ndarray): Preference thresholds for each criterion.
      w (numpy.ndarray): Weights for each criterion.

  Returns:
      numpy.ndarray: Ranking of the alternatives.
  """

  # Calculate positive and negative outranking flows
  s_plus = np.zeros((len(decision_matrix), len(decision_matrix)))
  s_minus = np.zeros((len(decision_matrix), len(decision_matrix)))
  for i in range(len(decision_matrix)):
    for j in range(len(decision_matrix)):
      if i != j:
        for k in range(len(criteria)):
          d_ij = decision_matrix[i, k] - decision_matrix[j, k]
          if d_ij > p_threshold[k]:
            s_plus[i, j] += w[k]
          elif d_ij < -p_threshold[k]:
            s_minus[i, j] += w[k]

  # Calculate net outranking flow
  net_flow = s_plus - s_minus

  # Calculate preference score
  preference_score = np.sum(net_flow, axis=1)

  # Rank the alternatives based on preference score
  ranking = np.argsort(preference_score)[::-1]

  return ranking

# Run the PROMETHEE II analysis
ranking = promethee_ii(decision_matrix, p_threshold, w)

# Print the ranking
print("Ranking of alternatives:", ranking + 1)  # Add 1 for human-readable indexing (1st, 2nd, ...)

Ranking of alternatives: [2 5 8 1 7 6 4 3 9]


In [ ]:
import numpy as np
import csv

# Define the data from the image table
data = {
    "Project name": ["Kamuthi Solar Park", "Pavagada Solar Park", "Kurnool Solar Park", "Nathpa Jhakri Dam", "Sardar Sarovar Dam", "Koyna Hydroelectric Project", "Tirunelvell Wind Farm", "Coimbatore Wind Farm", "Muppandal Wind Farm"],
    "Operating capacity (MW) (B)": [648, 1400, 1000, 1500, 1450, 1920, 1350, 1800, 1500],
    "Electricity (MWh/Yr)(B)": [1350000, 1600000, 1400000, 4000000, 5000000, 6000000, 3200000, 3500000, 3000000],
    "Construction period(yr)(NB)": [0.67, 2, 2, 10, 15, 1.5, 2, 1.5, 1.5],
    "Capacity factor (%(D))": [23.8, 13, 16.147, 55, 50, 60, 33, 38, 35],
    "Investments (NB) crores)": [4550, 14800, 7000, 22000, 25000, 30000, 19000, 22000, 20000],
    "O & M (Crores/Year)(NB)":[42, 130, 65, 180, 200, 220, 140, 160, 150],
    "Land (ha)(9) & M (Crores/Yr)(NB)": [42, 130, 65, 180, 200, 220, 140, 150, 150],
    "Jobs (NB)": [8500, 8000, 2500, 2200, 2500, 2800, 1400, 1800, 1500]
}

# Select the relevant criteria for your analysis
criteria = ["Operating capacity (MW) (B)", "Electricity (MWh/Yr)(B)", "Construction period(yr)(NB)", "Capacity factor (%(D))", "Investments (NB) crores)", "O & M (Crores/Year)(NB)", "Land (ha)(9) & M (Crores/Yr)(NB)", "Jobs (NB)"]

# Convert data into a NumPy array
decision_matrix = np.array([data[c] for c in criteria])
decision_matrix = np.vstack([decision_matrix, np.ones(len(data['Project name']))])  # Add a row for weights

# AHP Weights
w = np.array([0.782738095, 0.621428571, 0.25125, 0.683683333, 0.266325245, 0.303270896, 0.66547619, 0.70963925])

# Preference thresholds (replace with your values based on importance)
p_threshold = np.array([100, 500000, 1, 5, 2000, 90, 50, 500])

def promethee_ii(decision_matrix, p_threshold, w):
    """
    Performs PROMETHEE II MCDM method ranking.

    Args:
        decision_matrix (numpy.ndarray): Decision matrix with alternatives as rows and criteria as columns.
        p_threshold (numpy.ndarray): Preference thresholds for each criterion.
        w (numpy.ndarray): Weights for each criterion.

    Returns:
        numpy.ndarray: Ranking of the alternatives.
    """

    # Calculate positive and negative outranking flows
    s_plus = np.zeros((len(decision_matrix), len(decision_matrix)))
    s_minus = np.zeros((len(decision_matrix), len(decision_matrix)))
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j:
                for k in range(len(criteria)):
                    d_ij = decision_matrix[i, k] - decision_matrix[j, k]
                    if d_ij > p_threshold[k]:
                        s_plus[i, j] += w[k]
                    elif d_ij < -p_threshold[k]:
                        s_minus[i, j] += w[k]

    # Calculate net outranking flow
    net_flow = s_plus - s_minus

    # Calculate preference score
    preference_score = np.sum(net_flow, axis=1)

    # Rank the alternatives based on preference score
    ranking = np.argsort(preference_score)[::-1]

    return ranking

# Run the PROMETHEE II analysis
ranking = promethee_ii(decision_matrix, p_threshold, w)

print("AHP - PROMETHEE II")
# Print the ranking
print("Ranking of alternatives:", ranking + 1)  # Add 1 for human-readable indexing (1st, 2nd, ...)

# Save ranking to CSV file
with open('ranking.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Rank', 'Project name'])
    for i, idx in enumerate(ranking):
        writer.writerow([i + 1, data['Project name'][idx]])

# Print the ranking
print("Ranking of alternatives:")
for i, idx in enumerate(ranking):
    print(f"{i + 1}. {data['Project name'][idx]}")



AHP - PROMETHEE II
Ranking of alternatives: [2 5 8 1 7 6 4 3 9]
Ranking of alternatives:
1. Pavagada Solar Park
2. Sardar Sarovar Dam
3. Coimbatore Wind Farm
4. Kamuthi Solar Park
5. Tirunelvell Wind Farm
6. Koyna Hydroelectric Project
7. Nathpa Jhakri Dam
8. Kurnool Solar Park
9. Muppandal Wind Farm


ENTROPY weights
PROMETHEE II

In [ ]:
import numpy as np
import csv

# Define the data from the image table
data = {
    "Project name": ["Kamuthi Solar Park", "Pavagada Solar Park", "Kurnool Solar Park", "Nathpa Jhakri Dam", "Sardar Sarovar Dam", "Koyna Hydroelectric Project", "Tirunelvell Wind Farm", "Coimbatore Wind Farm", "Muppandal Wind Farm"],
    "Operating capacity (MW) (B)": [648, 1400, 1000, 1500, 1450, 1920, 1350, 1800, 1500],
    "Electricity (MWh/Yr)(B)": [1350000, 1600000, 1400000, 4000000, 5000000, 6000000, 3200000, 3500000, 3000000],
    "Construction period(yr)(NB)": [0.67, 2, 2, 10, 15, 1.5, 2, 1.5, 1.5],
    "Capacity factor (%(D))": [23.8, 13, 16.147, 55, 50, 60, 33, 38, 35],
    "Investments (NB) crores)": [4550, 14800, 7000, 22000, 25000, 30000, 19000, 22000, 20000],
    "O & M (Crores/Year)(NB)":[42, 130, 65, 180, 200, 220, 140, 160, 150],
    "Land (ha)(9) & M (Crores/Yr)(NB)": [42, 130, 65, 180, 200, 220, 140, 150, 150],
    "Jobs (NB)": [8500, 8000, 2500, 2200, 2500, 2800, 1400, 1800, 1500]
}

# Select the relevant criteria for your analysis
criteria = ["Operating capacity (MW) (B)", "Electricity (MWh/Yr)(B)", "Construction period(yr)(NB)", "Capacity factor (%(D))", "Investments (NB) crores)", "O & M (Crores/Year)(NB)", "Land (ha)(9) & M (Crores/Yr)(NB)", "Jobs (NB)"]

# Convert data into a NumPy array
decision_matrix = np.array([data[c] for c in criteria])
decision_matrix = np.vstack([decision_matrix, np.ones(len(data['Project name']))])  # Add a row for weights

# ENTROPY Weights
w = np.array([0.125298713, 0.124891216, 0.125505851, 0.125495345, 0.124420104, 0.125487997, 0.12520127, 0.123699503])

# Preference thresholds (replace with your values based on importance)
p_threshold = np.array([100, 500000, 1, 5, 2000, 90, 50, 500])

def promethee_ii(decision_matrix, p_threshold, w):
    """
    Performs PROMETHEE II MCDM method ranking.

    Args:
        decision_matrix (numpy.ndarray): Decision matrix with alternatives as rows and criteria as columns.
        p_threshold (numpy.ndarray): Preference thresholds for each criterion.
        w (numpy.ndarray): Weights for each criterion.

    Returns:
        numpy.ndarray: Ranking of the alternatives.
    """

    # Calculate positive and negative outranking flows
    s_plus = np.zeros((len(decision_matrix), len(decision_matrix)))
    s_minus = np.zeros((len(decision_matrix), len(decision_matrix)))
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j:
                for k in range(len(criteria)):
                    d_ij = decision_matrix[i, k] - decision_matrix[j, k]
                    if d_ij > p_threshold[k]:
                        s_plus[i, j] += w[k]
                    elif d_ij < -p_threshold[k]:
                        s_minus[i, j] += w[k]

    # Calculate net outranking flow
    net_flow = s_plus - s_minus

    # Calculate preference score
    preference_score = np.sum(net_flow, axis=1)

    # Rank the alternatives based on preference score
    ranking = np.argsort(preference_score)[::-1]

    return ranking

# Run the PROMETHEE II analysis
ranking = promethee_ii(decision_matrix, p_threshold, w)

print("ENTROPY - PROMETHEE II")
# Print the ranking
print("Ranking of alternatives:", ranking + 1)  # Add 1 for human-readable indexing (1st, 2nd, ...)

# Save ranking to CSV file
with open('ranking.csv', 'w', newline='') as csvfile:
    writer = csv.writer(csvfile)
    writer.writerow(['Rank', 'Project name'])
    for i, idx in enumerate(ranking):
        writer.writerow([i + 1, data['Project name'][idx]])

# Print the ranking
print("Ranking of alternatives:")
for i, idx in enumerate(ranking):
    print(f"{i + 1}. {data['Project name'][idx]}")




ENTROPY - PROMETHEE II
Ranking of alternatives: [2 5 8 1 7 6 4 3 9]
Ranking of alternatives:
1. Pavagada Solar Park
2. Sardar Sarovar Dam
3. Coimbatore Wind Farm
4. Kamuthi Solar Park
5. Tirunelvell Wind Farm
6. Koyna Hydroelectric Project
7. Nathpa Jhakri Dam
8. Kurnool Solar Park
9. Muppandal Wind Farm


ELECTRE III - AHP

In [ ]:
import numpy as np

def electre_iii(decision_matrix, w, s_bar, s_plus, s_minus, lambda_):
    """
    Performs an ELECTRE III MCDM analysis.

    Args:
        decision_matrix (numpy.ndarray): Decision matrix with alternatives as rows and criteria as columns.
        w (numpy.ndarray): Weights for each criterion.
        s_bar (float): Indifference threshold.
        s_plus (float): Preference threshold.
        s_minus (float): Veto threshold.
        lambda_ (float): Concordance index.

    Returns:
        tuple: (numpy.ndarray, numpy.ndarray)
            - concordance_matrix (numpy.ndarray): Concordance matrix.
            - discordance_matrix (numpy.ndarray): Discordance matrix.
    """

    # Calculate concordance and discordance scores
    concordance_matrix = np.zeros((len(decision_matrix), len(decision_matrix)))
    discordance_matrix = np.zeros((len(decision_matrix), len(decision_matrix)))
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j:
                d = np.abs(decision_matrix[i] - decision_matrix[j]) * w.reshape(-1, 1)
                c = np.sum(d <= s_bar)
                v = np.sum(d > s_plus)

                concordance_matrix[i, j] = c / len(w)

                if v == 0:  # Check if the array is empty
                    discordance_matrix[i, j] = 0
                else:
                    discordance_matrix[i, j] = np.max(d[d > s_minus]) / lambda_

    return concordance_matrix, discordance_matrix

# Replace with your data (assuming same criteria as before)
data = {
    "Operating capacity (MW) (B)": [648, 1400, 1000, 1500, 1450, 1920, 1350, 1800, 1500],
    "Electricity (MWh/Yr)(B)": [1350000, 1600000, 1400000, 4000000, 5000000, 6000000, 3200000, 3500000, 3000000],
    "Construction period(yr)(NB)": [0.67, 2, 2, 10, 15, 1.5, 2, 1.5, 1.5],
    "Capacity factor (%(D))": [23.8, 13, 16.147, 55, 50, 60, 33, 38, 35],
    "Investments (NB) crores)": [4550, 14800, 7000, 22000, 25000, 30000, 19000, 22000, 20000],
    "O & M (Crores/Year)(NB)": [42, 130, 65, 180, 200, 220, 140, 160, 150],
    "Land (ha)(9) & M (Crores/Yr)(NB)": [42, 130, 65, 180, 200, 220, 140, 150, 150],
    "Jobs (NB)": [8500, 8000, 2500, 2200, 2500, 2800, 1400, 1800, 1500]
}

criteria = list(data.keys())
decision_matrix = np.array([data[c] for c in criteria])

# Modify the decision matrix to have a shape of (9, 9)
decision_matrix = decision_matrix.T  # Transpose to make alternatives as rows

# Define parameters (replace with your judgments)
w = np.array([0.782738095, 0.621428571, 0.25125, 0.683683333, 0.266325245, 0.303270896, 0.66547619, 0.70963925])  # AHP Weights for criteria
s_bar = 25  # Indifference threshold
s_plus = 50  # Preference threshold
s_minus = 100  # Veto threshold
lambda_ = 2  # Concordance index

# Perform ELECTRE III analysis
result = electre_iii(decision_matrix, w, s_bar, s_plus, s_minus, lambda_)

print("AHP - ELECTRE III")
# Print the results
if result is not None:
    concordance_matrix, discordance_matrix = result
    print("Concordance matrix:")
    print(concordance_matrix)
    print("\nDiscordance matrix:")
    print(discordance_matrix)

    # Calculate net outranking flow (considering concordance and discordance)
    outranking_matrix = concordance_matrix - discordance_matrix

    print("\nOutranking matrix:")
    print(outranking_matrix)

    # Analyze the dominance relations
    dominant_alternatives = []
    dominated_alternatives = []
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j and outranking_matrix[i, j] > 0:
                dominant_alternatives.append((i, j))
            elif i != j and outranking_matrix[i, j] < 0:
                dominated_alternatives.append((i, j))

    print("\nDominant relations:")
    for i, j in dominant_alternatives:
        print(f"Alternative {i+1} dominates alternative {j+1}")
    print("\nDominated relations:")
    for i, j in dominated_alternatives:
        print(f"Alternative {i+1} is dominated by alternative {j+1}")
else:
    print("Error: ELECTRE III analysis failed.")

def calculate_credibility_scores(outranking_matrix):
  """
  Calculates credibility scores for each alternative based on the outranking matrix.

  Args:
      outranking_matrix (numpy.ndarray): Outranking matrix from ELECTRE III analysis.

  Returns:
      numpy.ndarray: Credibility scores for each alternative.
  """
  credibility_scores = np.sum(outranking_matrix, axis=1)  # Sum of each row (outranking received)
  return credibility_scores

# Calculate credibility scores
credibility_scores = calculate_credibility_scores(outranking_matrix)

# Sort alternatives by credibility scores (descending order)
sorted_alternatives = np.argsort(credibility_scores)[::-1]

# Print ranking based on credibility scores
print("\nRanking based on credibility scores:")
for i in range(len(sorted_alternatives)):
  print(f"Rank {i+1}: Alternative {sorted_alternatives[i]+1}")



def kernel_approach(outranking_matrix):
  """
  Identifies the kernel of non-dominated alternatives using the outranking matrix.

  Args:
      outranking_matrix (numpy.ndarray): Outranking matrix from ELECTRE III analysis.

  Returns:
      list: List of indices representing the kernel (non-dominated alternatives).
  """
  dominated = np.any(outranking_matrix < 0, axis=1)  # Check if any row has negative values (dominated)
  non_dominated_alternatives = np.where(~dominated)[0]  # Find non-dominated alternatives

  while True:
    previous_count = len(non_dominated_alternatives)
    new_dominated = np.any(outranking_matrix[non_dominated_alternatives[:, None], non_dominated_alternatives] < 0, axis=1)
    non_dominated_alternatives = non_dominated_alternatives[~new_dominated]
    if len(non_dominated_alternatives) == previous_count:
      break

  return non_dominated_alternatives.tolist()

# Find the kernel
kernel = kernel_approach(outranking_matrix)

# Print the kernel (non-dominated alternatives)
print("\nKernel (non-dominated alternatives):")
for i in kernel:
  print(f"Alternative {i+1}")

# Ranking based on credibility scores
with open('ranking_credibility.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerow(['Rank', 'Alternative'])
  for i in range(len(sorted_alternatives)):
    writer.writerow([i + 1, sorted_alternatives[i] + 1])

# Kernel (non-dominated alternatives)
with open('kernel.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerow(['Non-Dominated Alternative'])
  writer.writerows([[alternative + 1] for alternative in kernel])


AHP - ELECTRE III
Concordance matrix:
[[0.    2.5   4.    2.    2.    1.75  2.25  2.    2.   ]
 [2.5   0.    2.75  2.125 2.75  1.875 4.375 4.    4.   ]
 [4.    2.75  0.    1.5   2.875 1.375 2.75  2.375 2.5  ]
 [2.    2.125 1.5   0.    4.375 3.    3.    5.    5.   ]
 [2.    2.75  2.875 4.375 0.    4.    2.75  2.875 3.125]
 [1.75  1.875 1.375 3.    4.    0.    2.75  2.75  2.75 ]
 [2.25  4.375 2.75  3.    2.75  2.75  0.    4.    4.   ]
 [2.    4.    2.375 5.    2.875 2.75  4.    0.    4.   ]
 [2.    4.    2.5   5.    3.125 2.75  4.    4.    0.   ]]

Discordance matrix:
[[      0.         97842.261875   19568.452375 1037127.975875
  1428497.023375 1819866.070875  724032.737875  841443.452125
   645758.928375]
 [  97842.261875       0.         78273.8095    939285.714
  1330654.7615   1722023.809     626190.476     743601.19025
   547916.6665  ]
 [  19568.452375   78273.8095         0.       1017559.5235
  1408928.571    1800297.6185    704464.2855    821874.99975
   626190.476   ]
 [103712

ELECTRE III - ENTROPY

In [ ]:
import numpy as np

def electre_iii(decision_matrix, w, s_bar, s_plus, s_minus, lambda_):
    """
    Performs an ELECTRE III MCDM analysis.

    Args:
        decision_matrix (numpy.ndarray): Decision matrix with alternatives as rows and criteria as columns.
        w (numpy.ndarray): Weights for each criterion.
        s_bar (float): Indifference threshold.
        s_plus (float): Preference threshold.
        s_minus (float): Veto threshold.
        lambda_ (float): Concordance index.

    Returns:
        tuple: (numpy.ndarray, numpy.ndarray)
            - concordance_matrix (numpy.ndarray): Concordance matrix.
            - discordance_matrix (numpy.ndarray): Discordance matrix.
    """

    # Calculate concordance and discordance scores
    concordance_matrix = np.zeros((len(decision_matrix), len(decision_matrix)))
    discordance_matrix = np.zeros((len(decision_matrix), len(decision_matrix)))
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j:
                d = np.abs(decision_matrix[i] - decision_matrix[j]) * w.reshape(-1, 1)
                c = np.sum(d <= s_bar)
                v = np.sum(d > s_plus)

                concordance_matrix[i, j] = c / len(w)

                if v == 0:  # Check if the array is empty
                    discordance_matrix[i, j] = 0
                else:
                    discordance_matrix[i, j] = np.max(d[d > s_minus]) / lambda_

    return concordance_matrix, discordance_matrix

# Replace with your data (assuming same criteria as before)
data = {
    "Operating capacity (MW) (B)": [648, 1400, 1000, 1500, 1450, 1920, 1350, 1800, 1500],
    "Electricity (MWh/Yr)(B)": [1350000, 1600000, 1400000, 4000000, 5000000, 6000000, 3200000, 3500000, 3000000],
    "Construction period(yr)(NB)": [0.67, 2, 2, 10, 15, 1.5, 2, 1.5, 1.5],
    "Capacity factor (%(D))": [23.8, 13, 16.147, 55, 50, 60, 33, 38, 35],
    "Investments (NB) crores)": [4550, 14800, 7000, 22000, 25000, 30000, 19000, 22000, 20000],
    "O & M (Crores/Year)(NB)": [42, 130, 65, 180, 200, 220, 140, 160, 150],
    "Land (ha)(9) & M (Crores/Yr)(NB)": [42, 130, 65, 180, 200, 220, 140, 150, 150],
    "Jobs (NB)": [8500, 8000, 2500, 2200, 2500, 2800, 1400, 1800, 1500]
}

criteria = list(data.keys())
decision_matrix = np.array([data[c] for c in criteria])

# Modify the decision matrix to have a shape of (9, 9)
decision_matrix = decision_matrix.T  # Transpose to make alternatives as rows

# Define parameters (replace with your judgments)
w = np.array([0.125298713, 0.124891216, 0.125505851, 0.125495345, 0.124420104, 0.125487997, 0.12520127, 0.123699503])  # ENTROPY Weights for criteria
s_bar = 25  # Indifference threshold
s_plus = 50  # Preference threshold
s_minus = 100  # Veto threshold
lambda_ = 2  # Concordance index

# Perform ELECTRE III analysis
result = electre_iii(decision_matrix, w, s_bar, s_plus, s_minus, lambda_)

print("ENTROPY - ELECTRE III")
# Print the results
if result is not None:
    concordance_matrix, discordance_matrix = result
    print("Concordance matrix:")
    print(concordance_matrix)
    print("\nDiscordance matrix:")
    print(discordance_matrix)

    # Calculate net outranking flow (considering concordance and discordance)
    outranking_matrix = concordance_matrix - discordance_matrix

    print("\nOutranking matrix:")
    print(outranking_matrix)

    # Analyze the dominance relations
    dominant_alternatives = []
    dominated_alternatives = []
    for i in range(len(decision_matrix)):
        for j in range(len(decision_matrix)):
            if i != j and outranking_matrix[i, j] > 0:
                dominant_alternatives.append((i, j))
            elif i != j and outranking_matrix[i, j] < 0:
                dominated_alternatives.append((i, j))

    print("\nDominant relations:")
    for i, j in dominant_alternatives:
        print(f"Alternative {i+1} dominates alternative {j+1}")
    print("\nDominated relations:")
    for i, j in dominated_alternatives:
        print(f"Alternative {i+1} is dominated by alternative {j+1}")
else:
    print("Error: ELECTRE III analysis failed.")

def calculate_credibility_scores(outranking_matrix):
  """
  Calculates credibility scores for each alternative based on the outranking matrix.

  Args:
      outranking_matrix (numpy.ndarray): Outranking matrix from ELECTRE III analysis.

  Returns:
      numpy.ndarray: Credibility scores for each alternative.
  """
  credibility_scores = np.sum(outranking_matrix, axis=1)  # Sum of each row (outranking received)
  return credibility_scores

# Calculate credibility scores
credibility_scores = calculate_credibility_scores(outranking_matrix)

# Sort alternatives by credibility scores (descending order)
sorted_alternatives = np.argsort(credibility_scores)[::-1]

# Print ranking based on credibility scores
print("\nRanking based on credibility scores:")
for i in range(len(sorted_alternatives)):
  print(f"Rank {i+1}: Alternative {sorted_alternatives[i]+1}")



def kernel_approach(outranking_matrix):
  """
  Identifies the kernel of non-dominated alternatives using the outranking matrix.

  Args:
      outranking_matrix (numpy.ndarray): Outranking matrix from ELECTRE III analysis.

  Returns:
      list: List of indices representing the kernel (non-dominated alternatives).
  """
  dominated = np.any(outranking_matrix < 0, axis=1)  # Check if any row has negative values (dominated)
  non_dominated_alternatives = np.where(~dominated)[0]  # Find non-dominated alternatives

  while True:
    previous_count = len(non_dominated_alternatives)
    new_dominated = np.any(outranking_matrix[non_dominated_alternatives[:, None], non_dominated_alternatives] < 0, axis=1)
    non_dominated_alternatives = non_dominated_alternatives[~new_dominated]
    if len(non_dominated_alternatives) == previous_count:
      break

  return non_dominated_alternatives.tolist()

# Find the kernel
kernel = kernel_approach(outranking_matrix)

# Print the kernel (non-dominated alternatives)
print("\nKernel (non-dominated alternatives):")
for i in kernel:
  print(f"Alternative {i+1}")

# Ranking based on credibility scores
with open('ranking_credibility.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerow(['Rank', 'Alternative'])
  for i in range(len(sorted_alternatives)):
    writer.writerow([i + 1, sorted_alternatives[i] + 1])

# Kernel (non-dominated alternatives)
with open('kernel.csv', 'w', newline='') as csvfile:
  writer = csv.writer(csvfile)
  writer.writerow(['Non-Dominated Alternative'])
  writer.writerows([[alternative + 1] for alternative in kernel])


ENTROPY - ELECTRE III
Concordance matrix:
[[0. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 0. 4. 5. 5. 4. 5. 4. 5.]
 [4. 4. 0. 4. 5. 4. 4. 4. 4.]
 [4. 5. 4. 0. 5. 4. 5. 5. 5.]
 [4. 5. 5. 5. 0. 4. 5. 4. 5.]
 [4. 4. 4. 4. 4. 0. 4. 5. 4.]
 [4. 5. 4. 5. 5. 4. 0. 4. 6.]
 [4. 4. 4. 5. 4. 5. 4. 0. 4.]
 [4. 5. 4. 5. 5. 4. 6. 4. 0.]]

Discordance matrix:
[[     0.        15688.231375   3137.646275 166295.252575 229048.178075
  291801.103575 116092.912175 134918.789825 103542.327075]
 [ 15688.231375      0.        12550.5851   150607.0212   213359.9467
  276112.8722   100404.6808   119230.55845   87854.0957  ]
 [  3137.646275  12550.5851        0.       163157.6063   225910.5318
  288663.4573   112955.2659   131781.14355  100404.6808  ]
 [166295.252575 150607.0212   163157.6063        0.        62752.9255
  125505.851     50202.3404    31376.46275   62752.9255  ]
 [229048.178075 213359.9467   225910.5318    62752.9255        0.
   62752.9255   112955.2659    94129.38825  125505.851   ]
 [291801.103575 276112.